-- MySQL Script generated by MySQL Workbench
-- Thu Nov 27 10:33:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- Christopher e Cauan

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rapido&seguro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rapido&seguro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rapido&seguro` DEFAULT CHARACTER SET utf8 ;
USE `rapido&seguro` ;

-- -----------------------------------------------------
-- Table `rapido&seguro`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido&seguro`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapido&seguro`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido&seguro`.`telefones` (
  `id_telefone` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(20) NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_telefone`),
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  INDEX `fk_telefones_clientes1_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_telefones_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `rapido&seguro`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapido&seguro`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido&seguro`.`enderecos` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `complemento` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_enderecos_clientes1_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_enderecos_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `rapido&seguro`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapido&seguro`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido&seguro`.`pedidos` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_endereco` INT NOT NULL,
  `data_do_pedido` DATETIME NOT NULL,
  `tipo_de_entrega` ENUM('normal', 'urgente') NOT NULL,
  `distancia` DECIMAL(10,2) NOT NULL,
  `peso_da_carga` DECIMAL(10,2) NOT NULL,
  `valor_base_por_km` DECIMAL(10,2) NOT NULL,
  `valor_base_por_kg` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_pedidos_clientes1_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_pedidos_enderecos1_idx` (`id_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `rapido&seguro`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_enderecos1`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `rapido&seguro`.`enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapido&seguro`.`entregas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido&seguro`.`entregas` (
  `id_entrega` INT NOT NULL AUTO_INCREMENT,
  `id_pedido` INT NOT NULL,
  `valor_da_distancia` DECIMAL(10,2) NOT NULL,
  `valor_do_peso` DECIMAL(10,2) NOT NULL,
  `acrescimo` DECIMAL(10,2) NULL,
  `desconto` DECIMAL(10,2) NULL,
  `taxa_extra` DECIMAL(10,2) NULL,
  `valor_final` DECIMAL(10,2) NOT NULL,
  `status_entrega` ENUM('calculado', 'em transito', 'entregue', 'cancelado') NOT NULL,
  PRIMARY KEY (`id_entrega`),
  INDEX `fk_entregas_pedidos1_idx` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_entregas_pedidos1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `rapido&seguro`.`pedidos` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

ALTER TABLE pedidos
MODIFY data_do_pedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

DELIMITER $$

create trigger trg_calcular_entrega
after insert on pedidos
for each row
begin
	declare v_valor_distancia decimal(10,2);
    declare v_valor_peso decimal(10,2);
    declare v_valor_base decimal(10,2);
    declare v_acrescimo decimal(10,2);
    declare v_valor_final decimal(10,2);
    declare v_desconto decimal(10,2);
    declare v_taxa_extra decimal(10,2);
    
    -- Calcular valor da distancia
    set v_valor_distancia = new.distancia * new.valor_base_por_km;
    
    
    -- Calcular valor da carga
    set v_valor_peso = new.peso_da_carga * new.valor_base_por_kg;
    
    
    -- Calcular preco base
    set v_valor_base = v_valor_distancia + v_valor_peso;
    
    
    -- Calculando acrescimo de 20% se o tipo de entrega for 'urgente'
    if new.tipo_de_entrega = 'urgente' then
		set v_acrescimo = v_valor_base * 0.20;
    else
		set v_acrescimo = 0;
	end if;
    
    set v_valor_final = v_valor_base + v_acrescimo;
    
    
    -- Calculando o desconto de 10% se o valor final for maior que 500
    if v_valor_final > 500 then
		set v_desconto = v_valor_final * 0.10;
        set v_valor_final = v_valor_final - v_desconto;
	else
		set v_desconto = 0;
	end if;
    
    
    -- Calculando a taxa extra por peso 15 a mais se tiver peso superior a 50kg
    if new.peso_da_carga > 50 then
		set v_taxa_extra = 15;
		set v_valor_final = v_valor_final + v_taxa_extra;
    else
		set v_taxa_extra = 0;
	end if;
        
	
    -- Inserir na tabela entregas
    insert into entregas (id_pedido, valor_da_distancia, valor_do_peso, acrescimo, desconto, taxa_extra, valor_final, status_entrega) values
    (new.id_pedido, v_valor_distancia, v_valor_peso, v_acrescimo, v_desconto, v_taxa_extra, v_valor_final, 'calculado');
end $$
DELIMITER ;

-- Testando Trigger
INSERT INTO pedidos (id_cliente, id_endereco, tipo_de_entrega, distancia, peso_da_carga, valor_base_por_km, valor_base_por_kg) VALUES
(6,3, "Urgente", 40, 40, 2, 2);
